sudo: required
language: c
cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/martoon-00/assembly-sort-test/.stack-work"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc build --only-dependencies --jobs=4
script:
- ./build.sh test bench
